#!/usr/bin/env sh

set -eu

USER=deployer
TARGET=${1:-testing}

if [[ $TARGET == "production" ]]; then
  SERVER=api.miautohoy.com
  APP_PATH=/var/www/miautohoyapi/current
  SERVICE=miautohoyapi
  EXTRA_RSYNC_OPTIONS=""
else
  SERVER=api-test.miautohoy.com
  APP_PATH=/var/www/miautohoyapitest/current
  SERVICE=miautohoyapitest
  EXTRA_RSYNC_OPTIONS="--exclude newrelic.js"
fi

echo "Deploying to $TARGET, please wait..."

ssh $USER@$SERVER "mkdir -p $APP_PATH"
rsync -az --delete --exclude .git --exclude .gitignore \
  --exclude deploy --exclude node_modules \
  --exclude images $EXTRA_RSYNC_OPTIONS \
  -e ssh . $USER@$SERVER:$APP_PATH
ssh $USER@$SERVER "cd $APP_PATH && npm install"
ssh root@$SERVER "systemctl restart $SERVICE"

echo "Deploy finished"
