version: '3.8'

services:
  techmo-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'