

module.exports = (sequelize, DataTypes) => {
  const PublicationDetail = sequelize.define('PublicationDetail', {
    Alimentacion: DataTypes.STRING(30),
    Motor: DataTypes.STRING(30),
    Puertas: DataTypes.INTEGER,
    Clasificacion: DataTypes.STRING(30),
    Cabina: DataTypes.STRING(30),
    Carga: DataTypes.STRING(30),
    PesoTotal: DataTypes.STRING(30),
    VelocidadMax: DataTypes.STRING(30),
    Potencia: DataTypes.STRING(30),
    Largo: DataTypes.FLOAT,
    Ancho: DataTypes.FLOAT,
    Alto: DataTypes.FLOAT,

    Direccion: DataTypes.STRING(30),
    AireAcondicionado: DataTypes.BOOLEAN,
    Traccion: DataTypes.STRING(30),
    Importado: DataTypes.BOOLEAN,
    Caja: DataTypes.STRING(30),
    FrenosAbs: DataTypes.BOOLEAN,
    Airbag: DataTypes.BOOLEAN,
    Climatizador: DataTypes.STRING(30),
    FarosAntiniebla: DataTypes.BOOLEAN,
    TechoCorredizo: DataTypes.BOOLEAN,
    SensorEstacionamiento: DataTypes.STRING(30),
    AirbagLateral: DataTypes.BOOLEAN,
    AirbagCabezaConductor: DataTypes.BOOLEAN,
    AirbagCortina: DataTypes.BOOLEAN,
    AirbagRodilla: DataTypes.BOOLEAN,

    FijacionISOFIX: DataTypes.BOOLEAN,
    ControlDeTraccion: DataTypes.BOOLEAN,
    ControlDeEstabilidad: DataTypes.BOOLEAN,
    ControlDeDescenso: DataTypes.BOOLEAN,
    SistemaArranqueEnPendiente: DataTypes.BOOLEAN,
    ControlDinamicoConduccion: DataTypes.BOOLEAN,
    BloqueoDiferencial: DataTypes.BOOLEAN,
    RepartidorElectronicoDeFrenado: DataTypes.BOOLEAN,
    AsistenteDeFrenadoEmergencia: DataTypes.BOOLEAN,
    ReguladorParFrenado: DataTypes.BOOLEAN,
    
    TapizadoCuero: DataTypes.BOOLEAN,
    AsientosElectronicos: DataTypes.BOOLEAN,
    ComputadoraABordo: DataTypes.BOOLEAN,
    FarosDeXenon: DataTypes.BOOLEAN,
    LLantasDeAleacion: DataTypes.BOOLEAN,
    TechoPanoramico: DataTypes.BOOLEAN,
    SensorDeLluvia: DataTypes.BOOLEAN,
    SensorCrepuscular: DataTypes.BOOLEAN,
    IndicadorPresionNeumaticos: DataTypes.BOOLEAN,
    VolanteConLevas: DataTypes.BOOLEAN,
    Bluetooth: DataTypes.BOOLEAN,
    AsientosTermicos: DataTypes.BOOLEAN,
    RunFlat: DataTypes.BOOLEAN,
  }, {
    timestamps: false,
  });
  return PublicationDetail;
};
